server {
  listen          80;
  server_name     met-frontend;

  location /health {
    add_header 'Content-Type' 'text/plain';
    return 200 'OK';
  }

  location / {
    root /app;
    try_files $uri $uri/ /index.html;
  }
}
