parameters:
  - name: "serviceName"
    default: "meteo.frontend"
    type: string

jobs:
  - job:
    displayName: ${{ parameters.serviceName }} build and publish

    variables:
      frontendRoot: "$(Build.SourcesDirectory)/fiek-met/frontend"
      CI: false

    steps:
      - checkout: self
      - checkout: cicd

      # - bash: |
      #     curl -w "\nDNS=%{time_namelookup}\nCONNECT=%{time_connect}\nTTFB=%{time_starttransfer}\nTOTAL=%{time_total}\n" \
      #         -o /dev/null \
      #         -s https://nodejs.org/dist/index.json

      # - task: NodeTool@0
      #   inputs:
      #     versionSpec: 12.14.1
      #     retryCountOnDownloadFails: '5'
      #     delayBetweenRetries: '5000'
      #   displayName: Install Node.js 12.14.1

      - bash: |
          set -euxo pipefail

          NODE_VERSION=12.14.1
          NODE_DIR="$AGENT_TEMPDIRECTORY/node"

          mkdir -p "$NODE_DIR"

          curl -L \
            --connect-timeout 30 \
            -o node.tar.gz \
            "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz"

          tar -xzf node.tar.gz -C "$NODE_DIR" --strip-components=1
          echo "##vso[task.prependpath]$NODE_DIR/bin"
        displayName: Install Node 12.14.1 manually

      - script: |
          set -e
          npm install yarn -g
          yarn install
        displayName: "Install yarn"
        workingDirectory: $(frontendRoot)

      - script: |
          set -e
          echo "REACT_APP_API_URL=%REACT_APP_API_URL%" > .env
          echo "REACT_APP_ODIN_URL=%REACT_APP_ODIN_URL%" >> .env
          yarn generate-api-client
          yarn build
        displayName: "Build application"
        workingDirectory: $(frontendRoot)

      - script: |
          yarn test --passWithNoTests --coverage
        displayName: "Run tests"
        workingDirectory: $(frontendRoot)

      - task: ArchiveFiles@2
        displayName: "Create build artifact (*.zip)"
        inputs:
          rootFolderOrFile: "$(frontendRoot)/build"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/${{ parameters.serviceName }}_$(Build.BuildId).zip"
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "${{ parameters.serviceName }}"
          publishLocation: "Container"

      - task: Bash@3
        displayName: "Get commit hash"
        inputs:
          targetType: "inline"
          script: |
            GIT_SHA=$(git rev-parse --short=8 HEAD)
            echo "##vso[task.setvariable variable=GIT_SHA]$GIT_SHA"
            echo "##vso[build.updatebuildnumber]$GIT_SHA"
          workingDirectory: $(Build.SourcesDirectory)/fiek-met

      - task: CopyFiles@2
        displayName: copy cicd files to publish
        inputs:
          sourceFolder: "$(Build.SourcesDirectory)/meteo-cicd/frontend"
          Contents: "**"
          targetFolder: $(frontendRoot)
          OverWrite: true

      - task: Docker@2
        displayName: METEO METEO-ONPREM Push frontend docker image to Azure repository
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          containerRegistry: "svc-meteo-crmeteocommongwc01"
          repository: "${{ parameters.serviceName }}"
          command: "buildAndPush"
          Dockerfile: "$(frontendRoot)/Dockerfile"
          tags: |
            latest
            $(GIT_SHA)
