parameters:
  - name: serviceName
    default: meteo.frontend
    type: string

jobs:
  - job:
    displayName: ${{ parameters.serviceName }} build and publish

    variables:
      frontendRoot: $(Build.SourcesDirectory)/fiek-met/frontend

    steps:
      - checkout: self
        fetchDepth: 1
      - checkout: cicd
        fetchDepth: 1

      - task: Bash@3
        displayName: Install Node 12.14.1 manually
        inputs:
          targetType: inline
          script: |
            set -euxo pipefail

            NODE_VERSION=12.14.1
            NODE_DIR="$AGENT_TEMPDIRECTORY/node"

            mkdir -p "$NODE_DIR"

            curl -L \
              --connect-timeout 30 \
              -o node.tar.gz \
              "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz"

            tar -xzf node.tar.gz -C "$NODE_DIR" --strip-components=1
            echo "##vso[task.prependpath]$NODE_DIR/bin"

      - task: Bash@3
        displayName: Install yarn
        inputs:
          targetType: inline
          script: |
            set -e
            npm install yarn -g
            yarn install
          workingDirectory: $(frontendRoot)

      - task: Bash@3
        displayName: Build application
        inputs:
          targetType: inline
          script: |
            set -e
            echo "REACT_APP_API_URL=%REACT_APP_API_URL%" > .env
            echo "REACT_APP_ODIN_URL=%REACT_APP_ODIN_URL%" >> .env
            yarn generate-api-client
            yarn build
          workingDirectory: $(frontendRoot)

      - task: Bash@3
        displayName: Run tests
        inputs:
          targetType: inline
          script: |
            CI=true yarn test --passWithNoTests --coverage
          workingDirectory: $(frontendRoot)

      - task: ArchiveFiles@2
        displayName: Create zip artifact
        inputs:
          rootFolderOrFile: $(frontendRoot)/build
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.serviceName }}_$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        displayName: Publish build artifacts
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: ${{ parameters.serviceName }}
          publishLocation: Container

      - task: Bash@3
        displayName: Get commit hash
        inputs:
          targetType: inline
          script: |
            GIT_SHA=$(git rev-parse --short=8 HEAD)
            echo "##vso[task.setvariable variable=GIT_SHA]$GIT_SHA"
            echo "##vso[build.updatebuildnumber]$GIT_SHA"
          workingDirectory: $(Build.SourcesDirectory)/fiek-met

      - task: CopyFiles@2
        displayName: Copy CICD files to Docker context
        inputs:
          sourceFolder: $(Build.SourcesDirectory)/meteo-cicd/frontend
          Contents: "**"
          targetFolder: $(frontendRoot)
          OverWrite: true

      - task: Docker@2
        displayName: METEO METEO-ONPREM Push frontend docker image to Azure repository
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          containerRegistry: svc-meteo-crmeteocommongwc01
          repository: ${{ parameters.serviceName }}
          command: buildAndPush
          Dockerfile: $(frontendRoot)/Dockerfile
          tags: |
            latest
            $(GIT_SHA)
