parameters:
- name: "serviceName"
  default: "meteo.mek.mock.api"
  type: string

jobs:
- job:
  displayName: ${{ parameters.serviceName }} build and publish

  variables:
    buildConfiguration: "Release"
    dotnetRoot: "$(Build.SourcesDirectory)/Meteo.Mek.Mock"

  steps:
  - checkout: self
  - checkout: cicd

  - task: DotNetCoreCLI@2
    displayName: Backend MEK Mock - Build solution
    inputs:
      command: "build"
      projects: "$(dotnetRoot)/**/*.sln"
      arguments: "--configuration $(buildConfiguration) /p:TreatWarningsAsErrors=true /warnaserror"

  - task: DotNetCoreCLI@2
    displayName: Run C# - Unit & Component tests
    inputs:
      command: "test"
      projects: "$(dotnetRoot)/**/*.Test*.csproj"
      arguments: "--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura"
      nobuild: true

  - task: Bash@3
    displayName: "Get commit hash"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      targetType: "inline"
      script: |
        GIT_SHA=$(git rev-parse --short=8 HEAD)
        echo "##vso[task.setvariable variable=GIT_SHA]$GIT_SHA"
        echo "##vso[build.updatebuildnumber]$GIT_SHA"
      workingDirectory: $(dotnetRoot)

  - task: Docker@2
    displayName: METEO Push backend API docker image to Azure repository
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      containerRegistry: "MeteoCR"
      repository: "${{ parameters.serviceName }}"
      command: "buildAndPush"
      Dockerfile: "$(dotnetRoot)/Dockerfile"
      tags: |
        latest
        $(GIT_SHA)

