parameters:
  - name: serviceName
    default: meteo.backend.api
    type: string

jobs:
  - job:
    displayName: ${{ parameters.serviceName }} build and publish

    variables:
      dependencyScanningInjectionEnabled: false  # Azure Devops feature override
      DependencyScanning.Skip: true
      buildConfiguration: Release
      dotnetRoot: $(Build.SourcesDirectory)/fiek-met/backend

    steps:
      - checkout: self
        fetchDepth: 1
      - checkout: cicd
        fetchDepth: 1

      - task: Bash@3
        displayName: Install .NET 6 SDK manually
        inputs:
          targetType: inline
          script: |
            set -euxo pipefail

            DOTNET_ROOT="$(Agent.ToolsDirectory)/dotnet"
            mkdir -p "$DOTNET_ROOT"

            curl -L \
              https://dot.net/v1/dotnet-install.sh \
              -o dotnet-install.sh

            chmod +x dotnet-install.sh
            ./dotnet-install.sh \
              --channel 6.0 \
              --install-dir "$DOTNET_ROOT"
            echo "##vso[task.prependpath]$DOTNET_ROOT"

      - task: Bash@3
        displayName: Install dotnet tools
        inputs:
          targetType: inline
          script: |
            dotnet tool restore
          workingDirectory: $(dotnetRoot)

      - task: Bash@3
        displayName: Install libnetcdf-dev
        inputs:
          targetType: inline
          script: |
            sudo apt-get update
            sudo apt-get install libnetcdf-dev
          workingDirectory: $(dotnetRoot)

      - task: Bash@3
        displayName: Backend - Build solution
        inputs:
          targetType: inline
          script: |
            dotnet build --configuration $(buildConfiguration) /p:TreatWarningsAsErrors=true /warnaserror
          workingDirectory: $(dotnetRoot)

      - task: DotNetCoreCLI@2
        displayName: Run C# - Unit & Component tests
        inputs:
          command: test
          projects: "$(dotnetRoot)/**/*.Test*.csproj"
          arguments: --configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
          nobuild: true

      - task: Bash@3
        displayName: Get commit hash
        inputs:
          targetType: inline
          script: |
            GIT_SHA=$(git rev-parse --short=8 HEAD)
            echo "##vso[task.setvariable variable=GIT_SHA]$GIT_SHA"
            echo "##vso[build.updatebuildnumber]$GIT_SHA"
          workingDirectory: $(dotnetRoot)

      - task: CopyFiles@2
        displayName: Copy CICD files to Docker context
        inputs:
          sourceFolder: $(Build.SourcesDirectory)/meteo-cicd/backend
          contents: "**"
          targetFolder: $(dotnetRoot)
          OverWrite: true

      - task: Docker@2
        displayName: METEO Push backend API docker image to Azure repository
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          containerRegistry: svc-meteo-crmeteocommongwc01
          repository: ${{ parameters.serviceName }}
          command: buildAndPush
          Dockerfile: $(dotnetRoot)/Dockerfile
          tags: |
            latest
            $(GIT_SHA)

      - task: Docker@2
        displayName: METEO-ONPREM build backend API docker image to Azure repository
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          containerRegistry: svc-meteo-crmeteocommongwc01
          repository: ${{ parameters.serviceName }}.onprem
          command: Build
          Dockerfile: $(dotnetRoot)/Dockerfile.onprem
          arguments: --build-arg TAG=$(GIT_SHA)
          tags: |
            latest
            $(GIT_SHA)

      - task: Docker@2
        displayName: METEO-ONPREM push backend API docker image to Azure repository
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          containerRegistry: svc-meteo-crmeteocommongwc01
          repository: ${{ parameters.serviceName }}.onprem
          command: Push
          Dockerfile: $(dotnetRoot)/Dockerfile.onprem
          tags: |
            latest
            $(GIT_SHA)
