version: '3.4'
services:
  meteo.backend.python:
    container_name: meteo.backend.python
    image: meteocr.azurecr.io/meteo.backend.python:%IMAGE_TAG%
    restart: always
    ports:
      - 5000:5000
    networks:
      - fiek-met
    volumes:
      - combined_train_params:/usr/src/app/combined_train_params
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 12G
        reservations:
          cpus: '4'
          memory: 4G
    oom_kill_disable: true

networks:
  fiek-met:
    external: true

volumes:
  combined_train_params:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /forecast_data/combined_train_params
