server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name meteo.mvmetr.hu fiek-met.hu;

    client_max_body_size 5M;

    ssl_certificate     /etc/nginx/ssl/meteo.mvmetr.hu.crt;
    ssl_certificate_key /etc/nginx/ssl/meteo.mvmetr.hu.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

   # proxy_set_header Host $host;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        proxy_pass         http://localhost:8080;
    }
}

server {
    listen 9443 ssl;
    server_name meteo.mvmetr.hu fiek-met.hu;

    client_max_body_size 5M;

    ssl_certificate     /etc/nginx/ssl/meteo.mvmetr.hu.crt;
    ssl_certificate_key /etc/nginx/ssl/meteo.mvmetr.hu.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

   # proxy_set_header Host $host;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        proxy_pass         http://localhost:9090;
    }
}

server {
    listen 443 ssl;
    listen 9443 ssl;
    server_name meteoapi.mvmetr.hu api.fiek-met.hu;

    client_max_body_size 5M;

    ssl_certificate     /etc/nginx/ssl/meteo.mvmetr.hu.crt;
    ssl_certificate_key /etc/nginx/ssl/meteo.mvmetr.hu.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

   # proxy_set_header Host $host;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location /health {
        add_header 'Content-Type' 'text/plain';
        return 200 'HOST OK';
    }

    location /api/Estimate/CreateCombinedEstimates {
        proxy_pass         http://localhost:53135/api/Estimate/CreateCombinedEstimates;
        proxy_read_timeout 24h;
    }

    location /api/ForecastSync/ImportForecasts {
        proxy_pass         http://localhost:53135/api/ForecastSync/ImportForecasts;
        proxy_read_timeout 24h;
    }

    location /api/ForecastSync/ImportSolcastZipForecasts {
        proxy_pass         http://localhost:53135/api/ForecastSync/ImportSolcastZipForecasts;
        proxy_read_timeout 24h;
    }

    location / {
        proxy_pass         http://localhost:53135;
        proxy_read_timeout 5m;
    }
}